Add `CacheTimeControl` and tests for it
artipie/composer-adapter pull request #105
Opened 2021-04-01 14:59 UTC by genryxy

Part of #77 
Added  `CacheTimeControl` and tests for it. Read values from `cache/cache-info.json` and check expiration

2021-04-01 17:31 UTC, olenagerasimova requested changes
@genryxy thanks, please, check my suggestion

2021-04-01 17:31 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> + * Checking does saved item expire by comparing time value.
@genryxy I'd suggest rephrasing to 
 > Checking if saved item is expired by comparing time value.

2021-04-01 17:31 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +    static final Duration EXPIRATION = Duration.ofMinutes(10);
@genryxy I'd suggest to change this constant to a field

2021-04-01 17:31 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +        return this.repo.value(CacheTimeControl.CACHE_FILE)
@genryxy hm, are you sure this method should fail if this `cache/cache-info.json` does not exist? Seems like it would be better to return false in this case

2021-04-01 17:31 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +final class CacheTimeControl implements CacheControl {
@genryxy also, I'd suggest to move this class to asto. May be the best way here would be to create a ticker now and move it as soon as you are sure the implementation is convenient and good.

2021-04-02 06:08 UTC, genryxy commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +final class CacheTimeControl implements CacheControl {
@olenagerasimova I'll add the `todo` ticket, but seems there will be a problem because in this class `Repository` interface is used for interaction with storage. And this interface exists only in this adapter.

2021-04-02 06:19 UTC, genryxy commented
@olenagerasimova thanks, answered and corrected

2021-04-02 07:49 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +final class CacheTimeControl implements CacheControl {
@genryxy is it possible to change `Repository` to a `Storage`?

2021-04-02 08:42 UTC, genryxy commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +final class CacheTimeControl implements CacheControl {
@olenagerasimova I think it is impossible because `ComposerProxySlice` accept `Repository` as a parameter and from this class repository is passed down

2021-04-02 09:12 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
> +final class CacheTimeControl implements CacheControl {
@genryxy you can simply add method to obtain `Storage` from `Repository`, this will sort this put

2021-04-02 09:28 UTC, genryxy commented
@olenagerasimova thanks, created method for obtaining storage

2021-04-02 09:31 UTC, olenagerasimova approved these changes
@genryxy thanks, look good to me

2021-04-02 09:38 UTC, merged