Add IT for installation from cache
artipie/composer-adapter pull request #108
Opened 2021-04-19 13:12 UTC by genryxy

Closes #77 
Added IT case for installation from cache. Made class `ComposerStorageCache` public for using in `artipie` module

2021-04-19 15:14 UTC, olenagerasimova requested changes
@genryxy thanks, just one suggestion

2021-04-19 15:14 UTC, olenagerasimova commented on src/test/java/com/artipie/composer/http/proxy/CacheComposerIT.java
> +            ex.printStackTrace();
@genryxy hm, I'd suggest to use `Logger.error()` here to print exception

2021-04-20 06:25 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-04-20 07:10 UTC, olenagerasimova requested changes
@genryxy thanks, one more suggestions: let's, please, remove unnecessary suppression
`@SuppressWarnings("PMD.AvoidPrintStackTrace")`

2021-04-20 07:17 UTC, genryxy commented
@olenagerasimova removed unnecessary suppression

2021-04-20 07:23 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-04-20 07:23 UTC, merged