#64 - Removed base path support
artipie/composer-adapter pull request #65
Opened 2020-09-23 12:28 UTC by olegmoz

Closes #64 
Removed base path support

2020-09-23 13:02 UTC, olenagerasimova requested changes
@olegmoz one suggestion, take a look please

2020-09-23 13:02 UTC, olenagerasimova commented on src/test/java/com/artipie/composer/http/PhpComposerTest.java
> +            new RequestLine(RqMethod.GET, "/p/vendor/package.json").toString(),
@olegmoz I'd suggest adding test method to verify that `METHOD_NOT_ALLOWED` is returned when request method is not `get` or `put`

2020-09-23 13:47 UTC, olegmoz commented
@olenagerasimova thanks, added tests for multiple methods

2020-09-23 13:57 UTC, olenagerasimova approved these changes
@olegmoz thanks

2020-09-23 14:31 UTC, merged

2020-09-23 14:59 UTC, 0crat commented
Job `gh:artipie/composer-adapter#65` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/5ae7edc5-3ecd-498d-80c5-4d39c0a30077, version: 0.54.5, hash: ${buildNumber} -->

2020-09-24 13:06 UTC, olenagerasimova commented
@olegmoz can we release this adapter? Yegor already touched `.rultor`

2020-09-24 13:10 UTC, olegmoz commented
@olenagerasimova there are still problems with release, see https://github.com/artipie/composer-adapter/issues/64

2020-09-24 13:13 UTC, olenagerasimova commented
@olegmoz oh, I see, thanks