#78 - Use Testcontainers for IT
artipie/composer-adapter pull request #79
Opened 2021-02-16 07:02 UTC by genryxy

Closes #78 
Used Testcontainers for IT cases.
Updated `com.artipie.http` from `0.16.1` to `0.17.7` to use `RandomFreePort`.

2021-02-16 09:00 UTC, olenagerasimova requested changes
@genryxy one comment, please, take a look

2021-02-16 09:00 UTC, olenagerasimova commented on src/test/java/com/artipie/composer/RepositoryHttpIT.java
> +        this.temp = Files.createTempDirectory("");
@genryxy why not to use junit @TempDir in this test? It seems to be good practice as we do not have to care about test temp files manually

2021-02-16 09:08 UTC, genryxy commented on src/test/java/com/artipie/composer/RepositoryHttpIT.java
> +        this.temp = Files.createTempDirectory("");
@olenagerasimova I tried to use at first `@tempdir` but there was a test failure https://github.com/artipie/composer-adapter/runs/1908671792#step:6:2349 because failed to delete temporary directory.

2021-02-16 09:28 UTC, olenagerasimova commented on src/test/java/com/artipie/composer/RepositoryHttpIT.java
> +        this.temp = Files.createTempDirectory("");
@genryxy I faced this issue in rpm, this means, that not all resources, working with this temp directory, were properly closed. Could you please check?

2021-02-16 11:15 UTC, genryxy commented on src/test/java/com/artipie/composer/RepositoryHttpIT.java
> +        this.temp = Files.createTempDirectory("");
@olenagerasimova to tell the truth, I do not have other ideas how to close resources. 
I have testcontainer (close in `tearDown()`), vertx server for hosting repository (close in `tearDown()`) , vertx server for getting zip archive ((close in `tearDown()`), create `HttpURLConnection` (close in `finally` block), create `ZipOutputStream` (use try with resources).

2021-02-20 13:22 UTC, genryxy commented
@olenagerasimova could you please check. I added todo about problem with removing temporary directory

2021-02-20 13:30 UTC, olenagerasimova approved these changes
@genryxy thanks, looks good to merge

2021-02-20 13:30 UTC, merged

2021-02-20 14:09 UTC, 0crat commented
Job `gh:artipie/composer-adapter#79` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/65e74cd9-939d-4283-965a-474ef761427f, version: 0.55, hash: ${buildNumber} -->