#71 - Add auth IT for repository HTTP
artipie/composer-adapter pull request #82
Opened 2021-02-25 14:43 UTC by genryxy

Closes #71 
Added auth IT for repository HTTP

2021-02-25 16:33 UTC, olenagerasimova requested changes
@genryxy please, check my comment. Also, I do not completely follow how is it possible, that we are using two different storages here? We add package to one in `addPackage()` and `upload()` methods and install from the other one created in `start()` method...

2021-02-25 16:33 UTC, olenagerasimova commented on src/test/java/com/artipie/composer/http/RepositoryHttpAuthIT.java
> +    private void start(final TestAuthentication.User user) {
@genryxy I'd suggest the following change: move everything except url creation from this method into `setUp()` and rename this method into `url()` and make it return `String` url. Field `url` can be removed then

2021-02-25 16:48 UTC, genryxy commented
@olenagerasimova `upload()` is necessary to create remote server from which the package will be uploaded. And url for package is specified in `dist` section in `PackageSimple` class. The second storage is used for `PhpComposer` slice

2021-02-26 06:26 UTC, olenagerasimova commented
@genryxy thanks, got it, could you please still consider suggestion from review?

2021-02-26 07:02 UTC, genryxy commented
@olenagerasimova thanks, made changes

2021-02-26 07:21 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-02-26 07:35 UTC, merged

2021-02-26 08:17 UTC, 0crat commented
Job `gh:artipie/composer-adapter#82` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/b0a20f27-3829-40f2-b9ff-a187c7a35954, version: 0.55, hash: ${buildNumber} -->