#23 - Add basic for uploading zip archive
artipie/composer-adapter pull request #88
Opened 2021-03-04 14:37 UTC by genryxy

Part of #23 
Started to implement uploading zip archive

2021-03-04 14:51 UTC, olenagerasimova requested changes
@genryxy have a concern about regular expression, please, take a look

2021-03-04 14:51 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/AddZipSlice.java
> +    public static final Pattern PATH = Pattern.compile("^/(?<name>.*)-(?<version>.*).zip$");
@genryxy what are the rules for names and versions in composer? Version, for example, can [contain](https://en.wikipedia.org/wiki/Software_versioning) `-`: 
/project-1.2.0-b.2.zip
in this case, name = project-1.2.0, version = b.2

2021-03-04 18:04 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-03-05 06:40 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-03-05 06:40 UTC, merged

2021-03-05 07:12 UTC, 0crat commented
Job `gh:artipie/composer-adapter#88` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/af465360-370b-4128-a3c1-1cc5e8a3ae69, version: 0.55.1, hash: ${buildNumber} -->