#23 - Implement adding archive in asto repository
artipie/composer-adapter pull request #90
Opened 2021-03-09 20:34 UTC by genryxy

Part of #23 
Added implementation for uploading archive in `AstoRepository` and tests

2021-03-10 07:32 UTC, olenagerasimova requested changes
@genryxy thanks, just one suggestion

2021-03-10 07:32 UTC, olenagerasimova commented on src/main/java/com/artipie/composer/http/AddArchiveSlice.java
> +                            new Archive.Name(matcher.group(1), matcher.group("version")),
@genryxy let's address to the regex groups in the same style here - either by group name or by number

2021-03-11 05:46 UTC, genryxy commented
@olenagerasimova thanks, used group name for both cases

2021-03-11 06:37 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-03-11 06:37 UTC, merged

2021-03-11 07:08 UTC, 0crat commented
Job `gh:artipie/composer-adapter#90` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/becbcb8d-bba0-4697-b41b-c5412bbd3828, version: 0.55.1, hash: ${buildNumber} -->